import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Footer from "@/components/Footer";
import { GraduationCap } from "lucide-react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Grkn Akademi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased items-center justify-center flex flex-col w-full`}
      >
        <div className="py-3 px-8 border-b border-brown/10 w-full flex flex-row items-center justify-center gap-4 mb-8">
          <GraduationCap size={32} />
          <span className="text-xl font-medium text-brown">Grkn Akademi</span>
        </div>
        {children}
        <div className="p-4 w-full">
          <Footer />
        </div>
      </body>
    </html>
  );
}
