import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased items-center justify-center flex flex-col w-full`}
      >
        <div className="py-3 px-8 border-b border-brown/10 w-full flex flex-row items-center justify-center gap-4 mb-8">
          <Image
            src={"/icon.png"}
            alt="logo"
            width={200}
            height={200}
            className="w-10 h-10"
          />
          <span className="text-xl font-medium text-brown">Grkn Akademi</span>
        </div>
        {children}
      </body>
    </html>
  );
}
